In [1]:
import pandas as pd
import numpy as np

In [2]:
df_athens = pd.read_csv('athens.csv')
df_athens

,Date,Latitude,Longitude,station_name,Wind-Speed (U),Wind-Speed (V),Dewpoint Temp,Soil Temp,Total Percipitation,Vegitation (High),Vegitation (Low),Temp,Relative Humidity,PM10,PM2.5,NO2,O3,code,id
0,2020-05-01 00:00:00,38.150000,23.550000,Athens CAMS station 0,1.713115,-0.588855,10.046454,17.083554,0.000035,1.699026,2.244626,12.948856,82.578812,8.101824,6.200135,3.479941,76.28401,ACAMS00,45
1,2020-05-01 00:00:00,37.850000,23.750000,Athens CAMS station 9,1.960498,-0.937417,10.270286,17.909675,0.000037,1.743299,1.431182,14.011539,78.352731,10.520411,7.836725,17.563843,74.39110,ACAMS09,54
2,2020-05-01 00:00:00,38.150000,23.650000,Athens CAMS station 1,1.640985,-0.556073,9.700422,16.976489,0.000040,1.642665,2.172998,12.550690,82.840317,8.587352,6.306404,2.892315,74.56569,ACAMS01,46
3,2020-05-01 00:00:00,37.850000,23.850000,Athens CAMS station 10,2.003834,-0.971722,10.159251,17.993456,0.000036,1.753648,1.582832,14.261641,76.558915,10.917974,8.207660,17.196804,67.90412,ACAMS10,55
4,2020-05-01 00:00:00,37.850000,23.950000,Athens CAMS station 11,1.954063,-0.912335,9.993532,17.957935,0.000036,1.706804,1.806660,14.179075,76.140202,11.353168,8.217451,15.817172,67.63471,ACAMS11,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1726459,2023-05-29 23:00:00,37.932000,23.713000,SMYRNI,0.240230,-1.216293,13.464139,20.926649,0.000809,1.557783,1.392521,16.946201,79.994187,19.000000,20.736000,24.000000,62.00000,GR0031A,15
1726460,2023-05-29 23:00:00,37.901000,23.879000,KOROPI,0.075186,-1.339309,13.110978,21.116500,0.000581,1.663799,2.290440,17.310772,76.371899,22.000000,12.737628,15.000000,58.00000,GR0120A,21
1726461,2023-05-29 23:00:00,37.948063,23.728360,PANACEA_045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.490770,13.595480,NaN,NaN,PAN045,73
1726462,2023-05-29 23:00:00,37.977210,23.783016,National Technical University of Athens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.873333,13.720000,NaN,NaN,NTUA01,101
1726463,2023-05-29 23:00:00,37.978000,23.727000,ATHINAS,0.209901,-1.259627,13.790172,21.719023,0.000797,1.039985,1.013138,17.284556,79.951931,19.360000,18.053333,27.000000,NaN,GR0027A,9

In [3]:
df_athens.dtypes

Date                    object
Latitude               float64
Longitude              float64
station_name            object
Wind-Speed (U)         float64
Wind-Speed (V)         float64
Dewpoint Temp          float64
Soil Temp              float64
Total Percipitation    float64
Vegitation (High)      float64
Vegitation (Low)       float64
Temp                   float64
Relative Humidity      float64
PM10                   float64
PM2.5                  float64
NO2                    float64
O3                     float64
code                    object
id                       int64
dtype: object

In [4]:
df_athens['Date'] = pd.to_datetime(df_athens['Date'])

In [5]:
df_athens.columns

Index(['Date', 'Latitude', 'Longitude', 'station_name', 'Wind-Speed (U)',
       'Wind-Speed (V)', 'Dewpoint Temp', 'Soil Temp', 'Total Percipitation',
       'Vegitation (High)', 'Vegitation (Low)', 'Temp', 'Relative Humidity',
       'PM10', 'PM2.5', 'NO2', 'O3', 'code', 'id'],
      dtype='object')

In [6]:
len(df_athens.columns)

19

In [7]:
df_athens[df_athens.isnull().any(axis=1)].reset_index()

,index,Date,Latitude,Longitude,station_name,Wind-Speed (U),Wind-Speed (V),Dewpoint Temp,Soil Temp,Total Percipitation,Vegitation (High),Vegitation (Low),Temp,Relative Humidity,PM10,PM2.5,NO2,O3,code,id
0,28,2020-05-01 00:00:00,38.083630,23.700375,Ano Liosia (Perneri),1.542801,-0.602022,9.329610,16.811724,0.000050,1.680861,2.289204,11.751732,85.142672,11.838625,9.954234,12.530855,63.666874,NaN,89
1,29,2020-05-01 00:00:00,37.978000,23.727000,ATHINAS,1.941428,-0.999548,10.683342,18.271925,0.000041,1.056650,1.017622,13.887849,81.121429,229.000000,131.000000,NaN,NaN,GR0027A,9
2,32,2020-05-01 00:00:00,37.989967,23.708792,ATH-ENVICARE-3,2.009380,-1.119707,11.185055,18.745936,0.000041,0.450644,0.684208,13.997490,83.183875,229.000000,131.000000,NaN,NaN,ATHEN023,86
3,33,2020-05-01 00:00:00,38.040443,23.833649,ATHENS_01,1.726030,-0.735917,9.740093,17.569076,0.000047,1.597551,1.287751,13.523624,77.993012,14.538260,11.451291,NaN,NaN,ATHN001,87
4,34,2020-05-01 00:00:00,37.982040,23.794780,ATHENS_02,1.827617,-0.878582,10.030270,17.812905,0.000044,1.471124,0.785802,14.188421,76.102745,12.000000,13.000000,NaN,NaN,ATHN002,88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176016,1726447,2023-05-29 23:00:00,38.040443,23.833649,ATHENS_01,0.289962,-1.179780,13.220562,20.343453,0.000985,1.569434,1.282711,16.578436,80.566451,17.787500,16.412500,NaN,NaN,ATHN001,87
176017,1726455,2023-05-29 23:00:00,37.989967,23.708792,ATH-ENVICARE-3,0.176714,-1.305320,14.187760,22.675439,0.000758,0.445583,0.680323,17.708009,79.856782,32.000000,21.538462,NaN,NaN,ATHEN023,86
176018,1726461,2023-05-29 23:00:00,37.948063,23.728360,PANACEA_045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.490770,13.595480,NaN,NaN,PAN045,73
176019,1726462,2023-05-29 23:00:00,37.977210,23.783016,National Technical University of Athens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.873333,13.720000,NaN,NaN,NTUA01,101
176020,1726463,2023-05-29 23:00:00,37.978000,23.727000,ATHINAS,0.209901,-1.259627,13.790172,21.719023,0.000797,1.039985,1.013138,17.284556,79.951931,19.360000,18.053333,27.000000,NaN,GR0027A,9

In [8]:
(df_athens.isnull().sum() / len(df_athens) * 100).sort_values(ascending=False)

O3                     8.576142
NO2                    8.299797
code                   1.562500
Total Percipitation    0.496564
Vegitation (Low)       0.496564
Relative Humidity      0.496564
Wind-Speed (U)         0.496564
Vegitation (High)      0.496564
Wind-Speed (V)         0.496564
Dewpoint Temp          0.496564
Soil Temp              0.496564
Temp                   0.438179
Longitude              0.000000
Date                   0.000000
Latitude               0.000000
station_name           0.000000
PM10                   0.000000
PM2.5                  0.000000
id                     0.000000
dtype: float64

In [9]:
df_athens["station_name"].value_counts()

station_name
Athens CAMS station 0     26976
Athens CAMS station 9     26976
Athens CAMS station 1     26976
Athens CAMS station 10    26976
Athens CAMS station 11    26976
                          ...
PANACEA_AirPaP_002        26976
PANACEA_AirPaP_006        26976
PANACEA_AirPaP_008        26976
PPCITY12                  26976
PANACEA_006               26976
Name: count, Length: 64, dtype: int64

In [10]:
df_athens["code"].isna().sum()

np.int64(26976)

In [11]:
df_athens['code'] = df_athens['code'].fillna('ANO001')

In [12]:
(df_athens.isnull().sum() / len(df_athens) * 100).sort_values(ascending=False)

O3                     8.576142
NO2                    8.299797
Wind-Speed (U)         0.496564
Relative Humidity      0.496564
Vegitation (Low)       0.496564
Dewpoint Temp          0.496564
Wind-Speed (V)         0.496564
Vegitation (High)      0.496564
Total Percipitation    0.496564
Soil Temp              0.496564
Temp                   0.438179
Longitude              0.000000
Latitude               0.000000
Date                   0.000000
station_name           0.000000
PM2.5                  0.000000
PM10                   0.000000
code                   0.000000
id                     0.000000
dtype: float64

In [13]:
cols = [
    "Vegitation (High)", "Wind-Speed (U)", "Wind-Speed (V)", 
    "Dewpoint Temp", "Soil Temp", "Total Percipitation", 
    "Vegitation (Low)", "Relative Humidity"
]

In [14]:
same_missing_pattern = df_athens[cols].isna().eq(df_athens[cols[0]].isna(), axis=0).all().all()

print("Do all these columns have the same missing pattern?", same_missing_pattern)

Do all these columns have the same missing pattern? True

In [15]:
df_athens.iloc[[463892]]

,Date,Latitude,Longitude,station_name,Wind-Speed (U),Wind-Speed (V),Dewpoint Temp,Soil Temp,Total Percipitation,Vegitation (High),Vegitation (Low),Temp,Relative Humidity,PM10,PM2.5,NO2,O3,code,id
463892,2021-02-27,38.013317,23.647491,PANACEA_014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.031614,NaN,43.575862,22.39247,36.0,32.0,PAN014,99

In [16]:
cols_to_fill = [
    "Vegitation (High)", "Wind-Speed (U)", "Wind-Speed (V)", 
    "Dewpoint Temp", "Soil Temp", "Total Percipitation", 
    "Vegitation (Low)", "Relative Humidity"
]

original_index = df_athens.index
original_order = df_athens.copy()

df_athens = df_athens.sort_values(['station_name', 'Date'])
df_athens[cols_to_fill] = df_athens.groupby('station_name')[cols_to_fill].fillna(method='ffill')
df_athens = df_athens.reindex(original_index)

C:\Users\valmi\AppData\Local\Temp\ipykernel_18224\3800076259.py:11: FutureWarning: DataFrameGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use DataFrame.fillna instead
  df_athens[cols_to_fill] = df_athens.groupby('station_name')[cols_to_fill].fillna(method='ffill')
C:\Users\valmi\AppData\Local\Temp\ipykernel_18224\3800076259.py:11: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_athens[cols_to_fill] = df_athens.groupby('station_name')[cols_to_fill].fillna(method='ffill')

In [17]:
df_athens.iloc[[463850]]

,Date,Latitude,Longitude,station_name,Wind-Speed (U),Wind-Speed (V),Dewpoint Temp,Soil Temp,Total Percipitation,Vegitation (High),Vegitation (Low),Temp,Relative Humidity,PM10,PM2.5,NO2,O3,code,id
463850,2021-02-26 23:00:00,38.013317,23.647491,PANACEA_014,0.702335,-1.628909,5.989872,11.108342,9.936383e-07,1.507902,1.124172,6.754565,94.904331,56.77,22.428232,51.0,25.0,PAN014,99

In [18]:
(df_athens.isnull().sum() / len(df_athens) * 100).sort_values(ascending=False)

O3                     8.576142
NO2                    8.299797
Temp                   0.438179
Longitude              0.000000
Latitude               0.000000
Date                   0.000000
station_name           0.000000
Soil Temp              0.000000
Wind-Speed (U)         0.000000
Wind-Speed (V)         0.000000
Dewpoint Temp          0.000000
Vegitation (Low)       0.000000
Vegitation (High)      0.000000
Total Percipitation    0.000000
Relative Humidity      0.000000
PM2.5                  0.000000
PM10                   0.000000
code                   0.000000
id                     0.000000
dtype: float64

In [19]:
original_index = df_athens.index

df_athens_sorted = df_athens.sort_values(['station_name', 'Date']).copy()

df_athens_sorted['Temp'] = (
    df_athens_sorted
    .groupby('station_name')['Temp']
    .transform(lambda x: x.interpolate(method='linear', limit_direction='both'))
)

df_athens = df_athens_sorted.reindex(original_index)

In [20]:
(df_athens.isnull().sum() / len(df_athens) * 100).sort_values(ascending=False)

O3                     8.576142
NO2                    8.299797
Date                   0.000000
Longitude              0.000000
Latitude               0.000000
station_name           0.000000
Wind-Speed (U)         0.000000
Soil Temp              0.000000
Total Percipitation    0.000000
Wind-Speed (V)         0.000000
Dewpoint Temp          0.000000
Vegitation (Low)       0.000000
Vegitation (High)      0.000000
Temp                   0.000000
Relative Humidity      0.000000
PM2.5                  0.000000
PM10                   0.000000
code                   0.000000
id                     0.000000
dtype: float64

In [21]:
stations_under_10300_O3 = (
    df_athens[df_athens['O3'].isna()]
    ['station_name']
    .value_counts()
    .loc[lambda x: x < 10300]
    .index
)

stations_under_10300_NO2 = (
    df_athens[df_athens['NO2'].isna()]
    ['station_name']
    .value_counts()
    .loc[lambda x: x < 10300]
    .index
)

df_athens = df_athens.sort_values(['station_name', 'Date'])
df_athens.loc[
    df_athens['station_name'].isin(stations_under_10300_O3), 'O3'
] = (
    df_athens[df_athens['station_name'].isin(stations_under_10300_O3)]
    .groupby('station_name')['O3']
    .fillna(method='ffill')
)

df_athens.loc[
    df_athens['station_name'].isin(stations_under_10300_NO2), 'NO2'
] = (
    df_athens[df_athens['station_name'].isin(stations_under_10300_NO2)]
    .groupby('station_name')['NO2']
    .fillna(method='ffill')
)

df_athens = df_athens.reindex(original_index)

C:\Users\valmi\AppData\Local\Temp\ipykernel_18224\2195111783.py:23: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  .fillna(method='ffill')
C:\Users\valmi\AppData\Local\Temp\ipykernel_18224\2195111783.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  .fillna(method='ffill')
C:\Users\valmi\AppData\Local\Temp\ipykernel_18224\2195111783.py:31: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  .fillna(method='ffill')
C:\Users\valmi\AppData\Local\Temp\ipykernel_18224\2195111783.py:31: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  .fillna(method='ffill')

In [22]:
(df_athens.isnull().sum() / len(df_athens) * 100).sort_values(ascending=False)

NO2                    7.812674
O3                     7.812674
Date                   0.000000
Longitude              0.000000
Latitude               0.000000
station_name           0.000000
Wind-Speed (U)         0.000000
Soil Temp              0.000000
Total Percipitation    0.000000
Wind-Speed (V)         0.000000
Dewpoint Temp          0.000000
Vegitation (Low)       0.000000
Vegitation (High)      0.000000
Temp                   0.000000
Relative Humidity      0.000000
PM2.5                  0.000000
PM10                   0.000000
code                   0.000000
id                     0.000000
dtype: float64

In [23]:
df_athens[df_athens['O3'].isna()]["station_name"].value_counts()

station_name
ATH-ENVICARE-3                     26976
ATHENS_01                          26976
CleanAir in Greece - Thiseio II    26976
ATHENS_02                          26976
CleanAir in Greece - Thiseio       26976
ATHINAS                                3
Name: count, dtype: int64

In [24]:
df_athens.loc[df_athens['station_name'] == 'ATHINAS', 'NO2'] = (
    df_athens.loc[df_athens['station_name'] == 'ATHINAS', 'NO2'].fillna(35.0)
)
df_athens.loc[df_athens['station_name'] == 'ATHINAS', 'O3'] = (
    df_athens.loc[df_athens['station_name'] == 'ATHINAS', 'O3'].fillna(2.0)
)

In [25]:
df_athens[df_athens['O3'].isna()]["station_name"].value_counts()

station_name
ATH-ENVICARE-3                     26976
ATHENS_01                          26976
ATHENS_02                          26976
CleanAir in Greece - Thiseio II    26976
CleanAir in Greece - Thiseio       26976
Name: count, dtype: int64

In [26]:
df_pivot = df_athens.pivot_table(
    index='Date',
    columns='station_name',
    values='PM2.5'
)
df_pivot

station_name,ARISTOTELOUS,ATH-ENVICARE-0,ATH-ENVICARE-2,ATH-ENVICARE-3,ATHENS_01,ATHENS_02,ATHINAS,Ano Liosia (Perneri),Athens CAMS station 0,Athens CAMS station 1,...,PANACEA_AirPaP_001,PANACEA_AirPaP_002,PANACEA_AirPaP_006,PANACEA_AirPaP_008,PARASKEVI,PERISTERI,PPCITY12,PPCITY21,SMYRNI,THRAKOMAKEDONES
Date,,,,,,,,,,,,,,,,,,,,,
2020-05-01 00:00:00,131.0,131.000000,10.683514,131.000000,11.451291,13.000000,131.000000,9.954234,6.200135,6.306404,...,11.451291,131.000000,9.493142,9.493142,13.0,9.954234,131.000000,131.000000,10.469307,15.0
2020-05-01 01:00:00,140.0,140.000000,10.468672,140.000000,10.161569,10.000000,140.000000,10.004467,6.743588,6.821030,...,10.161569,140.000000,11.157607,11.157607,10.0,10.004467,140.000000,140.000000,11.987478,11.0
2020-05-01 02:00:00,131.0,131.000000,10.439608,131.000000,9.567772,15.000000,131.000000,9.706072,5.907382,6.345460,...,9.567772,131.000000,11.452366,11.452366,15.0,9.706072,131.000000,131.000000,12.428730,20.0
2020-05-01 03:00:00,109.0,109.000000,10.487819,109.000000,9.537518,11.000000,109.000000,9.470734,6.022633,6.197413,...,9.537518,109.000000,10.987174,10.987174,11.0,9.470734,109.000000,109.000000,12.986314,8.0
2020-05-01 04:00:00,59.0,59.000000,10.025481,59.000000,9.273329,12.000000,59.000000,9.136471,5.962640,5.968396,...,9.273329,59.000000,10.538656,10.538656,12.0,9.136471,59.000000,59.000000,12.205142,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-05-29 19:00:00,17.0,22.582609,14.937931,23.609091,21.810000,12.414286,22.582609,10.733333,10.272034,9.316439,...,10.558621,16.775000,16.103846,25.614815,8.0,16.607692,11.823333,23.275000,25.614815,10.0
2023-05-29 20:00:00,16.0,18.234483,14.014286,23.120000,21.681818,24.200000,18.234483,20.988889,9.631711,9.220932,...,11.020000,16.880000,15.554545,29.668966,8.0,19.925926,12.663333,23.924138,29.668966,14.0
2023-05-29 21:00:00,15.0,15.079310,16.960714,28.909091,14.810000,21.590000,15.079310,16.290000,9.266436,9.783000,...,11.765517,19.888889,16.118519,21.760714,9.0,18.713793,13.036667,17.968966,21.760714,12.0
2023-05-29 22:00:00,15.0,17.544828,18.841379,19.833333,14.290000,14.113793,17.544828,15.190000,8.220789,9.035696,...,11.973333,17.240000,16.942857,21.255556,9.0,16.844828,11.580000,12.758621,21.255556,18.0
2023-05-29 23:00:00,16.0,18.053333,22.665517,21.538462,16.412500,13.720000,18.053333,12.277778,8.051229,7.414128,...,13.833333,19.320000,16.265000,20.736000,11.0,18.900000,12.856667,12.918182,20.736000,7.0

In [27]:
corr = df_pivot.corr()
corr.index.name = None
corr

station_name,ARISTOTELOUS,ATH-ENVICARE-0,ATH-ENVICARE-2,ATH-ENVICARE-3,ATHENS_01,ATHENS_02,ATHINAS,Ano Liosia (Perneri),Athens CAMS station 0,Athens CAMS station 1,...,PANACEA_AirPaP_001,PANACEA_AirPaP_002,PANACEA_AirPaP_006,PANACEA_AirPaP_008,PARASKEVI,PERISTERI,PPCITY12,PPCITY21,SMYRNI,THRAKOMAKEDONES
ARISTOTELOUS,1.000000,0.393787,0.507643,0.679509,0.423815,0.337891,0.393787,0.425501,0.250694,0.256402,...,0.426783,0.646124,0.549174,0.596985,0.346003,0.516159,0.762257,0.761672,0.594799,0.268561
ATH-ENVICARE-0,0.393787,1.000000,0.358587,0.398883,0.308364,0.271592,1.000000,0.307701,0.145011,0.148196,...,0.308223,0.363194,0.354980,0.407830,0.132280,0.330928,0.391520,0.463920,0.407982,0.099013
ATH-ENVICARE-2,0.507643,0.358587,1.000000,0.782763,0.834086,0.577095,0.358587,0.759535,0.268510,0.287352,...,0.844881,0.653871,0.801744,0.778565,0.222183,0.867180,0.580238,0.677304,0.780343,0.179808
ATH-ENVICARE-3,0.679509,0.398883,0.782763,1.000000,0.672611,0.488583,0.398883,0.650640,0.245169,0.257100,...,0.671885,0.720622,0.862421,0.830005,0.236129,0.839879,0.756113,0.826243,0.829673,0.180029
ATHENS_01,0.423815,0.308364,0.834086,0.672611,1.000000,0.664393,0.308364,0.758285,0.351952,0.374458,...,0.985026,0.697782,0.723187,0.687281,0.281230,0.767891,0.545681,0.628066,0.689230,0.221958
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PERISTERI,0.516159,0.330928,0.867180,0.839879,0.767891,0.526113,0.330928,0.762548,0.284339,0.298833,...,0.765916,0.616538,0.846801,0.778882,0.219037,1.000000,0.575392,0.665568,0.779423,0.181975
PPCITY12,0.762257,0.391520,0.580238,0.756113,0.545681,0.462253,0.391520,0.524610,0.291994,0.301629,...,0.547605,0.835147,0.617387,0.622410,0.275575,0.575392,1.000000,0.879847,0.617798,0.218716
PPCITY21,0.761672,0.463920,0.677304,0.826243,0.628066,0.536739,0.463920,0.604946,0.334073,0.347401,...,0.628563,0.807833,0.723119,0.776989,0.296794,0.665568,0.879847,1.000000,0.774811,0.239897
SMYRNI,0.594799,0.407982,0.780343,0.829673,0.689230,0.499660,0.407982,0.649278,0.310213,0.322374,...,0.692522,0.587015,0.872031,0.997924,0.236750,0.779423,0.617798,0.774811,1.000000,0.170421
THRAKOMAKEDONES,0.268561,0.099013,0.179808,0.180029,0.221958,0.300579,0.099013,0.247127,0.388156,0.402091,...,0.217694,0.267927,0.190999,0.170997,0.478560,0.181975,0.218716,0.239897,0.170421,1.000000

In [28]:
results = []

corr_matrix = corr.copy()

for column in corr_matrix.columns:
    top_2 = corr_matrix[column].nlargest(2)
    second_corr = top_2.iloc[1]
    second_station = top_2.index[1]
    
    results.append({
        'Station': column,
        'Second_Most_Correlated_With': second_station,
        'Correlation_Value': second_corr,
        'Correlation_Percentage': f"{second_corr*100:.1f}%"
    })

results_df = pd.DataFrame(results)
results_df

,Station,Second_Most_Correlated_With,Correlation_Value,Correlation_Percentage
0,ARISTOTELOUS,PPCITY12,0.762257,76.2%
1,ATH-ENVICARE-0,ATHINAS,1.000000,100.0%
2,ATH-ENVICARE-2,MAROUSI,0.873653,87.4%
3,ATH-ENVICARE-3,PANACEA_029,0.897801,89.8%
4,ATHENS_01,PANACEA_AirPaP_001,0.985026,98.5%
...,...,...,...,...
59,PERISTERI,PANACEA_019,0.883139,88.3%
60,PPCITY12,PPCITY21,0.879847,88.0%
61,PPCITY21,CleanAir in Greece - Thiseio,0.930175,93.0%
62,SMYRNI,PANACEA_AirPaP_008,0.997924,99.8%
63,THRAKOMAKEDONES,PANACEA_032,0.663706,66.4%

In [29]:
results_df[results_df["Station"] == "ATHENS_01"]

,Station,Second_Most_Correlated_With,Correlation_Value,Correlation_Percentage
4,ATHENS_01,PANACEA_AirPaP_001,0.985026,98.5%

In [30]:
results_df[results_df["Station"] == "ATHENS_02"]

,Station,Second_Most_Correlated_With,Correlation_Value,Correlation_Percentage
5,ATHENS_02,National Technical University of Athens,0.880073,88.0%

In [31]:
results_df[results_df["Station"] == "ATH-ENVICARE-3"]

,Station,Second_Most_Correlated_With,Correlation_Value,Correlation_Percentage
3,ATH-ENVICARE-3,PANACEA_029,0.897801,89.8%

In [32]:
station_mapping = {
    'ATHENS_01': 'PANACEA_AirPaP_001', 
    'ATHENS_02': 'National Technical University of Athens',
    'ATH-ENVICARE-3': 'PANACEA_029',
    'CleanAir in Greece - Thiseio': 'PPCITY21',
    'CleanAir in Greece - Thiseio II': 'PPCITY21',
}

cols_to_copy = ["O3", "NO2"]

for target, source in station_mapping.items():
    for col in cols_to_copy:
        df_athens.loc[df_athens["station_name"] == target, col] = (
            df_athens.loc[df_athens["station_name"] == source, col].values
        )

In [33]:
df_athens

,Date,Latitude,Longitude,station_name,Wind-Speed (U),Wind-Speed (V),Dewpoint Temp,Soil Temp,Total Percipitation,Vegitation (High),Vegitation (Low),Temp,Relative Humidity,PM10,PM2.5,NO2,O3,code,id
0,2020-05-01 00:00:00,38.150000,23.550000,Athens CAMS station 0,1.713115,-0.588855,10.046454,17.083554,0.000035,1.699026,2.244626,12.948856,82.578812,8.101824,6.200135,3.479941,76.28401,ACAMS00,45
1,2020-05-01 00:00:00,37.850000,23.750000,Athens CAMS station 9,1.960498,-0.937417,10.270286,17.909675,0.000037,1.743299,1.431182,14.011539,78.352731,10.520411,7.836725,17.563843,74.39110,ACAMS09,54
2,2020-05-01 00:00:00,38.150000,23.650000,Athens CAMS station 1,1.640985,-0.556073,9.700422,16.976489,0.000040,1.642665,2.172998,12.550690,82.840317,8.587352,6.306404,2.892315,74.56569,ACAMS01,46
3,2020-05-01 00:00:00,37.850000,23.850000,Athens CAMS station 10,2.003834,-0.971722,10.159251,17.993456,0.000036,1.753648,1.582832,14.261641,76.558915,10.917974,8.207660,17.196804,67.90412,ACAMS10,55
4,2020-05-01 00:00:00,37.850000,23.950000,Athens CAMS station 11,1.954063,-0.912335,9.993532,17.957935,0.000036,1.706804,1.806660,14.179075,76.140202,11.353168,8.217451,15.817172,67.63471,ACAMS11,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1726459,2023-05-29 23:00:00,37.932000,23.713000,SMYRNI,0.240230,-1.216293,13.464139,20.926649,0.000809,1.557783,1.392521,16.946201,79.994187,19.000000,20.736000,24.000000,62.00000,GR0031A,15
1726460,2023-05-29 23:00:00,37.901000,23.879000,KOROPI,0.075186,-1.339309,13.110978,21.116500,0.000581,1.663799,2.290440,17.310772,76.371899,22.000000,12.737628,15.000000,58.00000,GR0120A,21
1726461,2023-05-29 23:00:00,37.948063,23.728360,PANACEA_045,-0.012447,-4.024046,0.817448,16.663882,0.000117,1.462879,1.247304,17.860900,31.921052,20.490770,13.595480,9.606083,100.65001,PAN045,73
1726462,2023-05-29 23:00:00,37.977210,23.783016,National Technical University of Athens,-0.491393,-3.956621,12.422827,20.905300,0.000786,1.469335,0.926387,22.035118,54.449878,14.873333,13.720000,5.000000,99.00000,NTUA01,101
1726463,2023-05-29 23:00:00,37.978000,23.727000,ATHINAS,0.209901,-1.259627,13.790172,21.719023,0.000797,1.039985,1.013138,17.284556,79.951931,19.360000,18.053333,27.000000,9.00000,GR0027A,9

In [34]:
(df_athens.isnull().sum() / len(df_athens) * 100).sort_values(ascending=False)

Date                   0.0
Latitude               0.0
Longitude              0.0
station_name           0.0
Wind-Speed (U)         0.0
Wind-Speed (V)         0.0
Dewpoint Temp          0.0
Soil Temp              0.0
Total Percipitation    0.0
Vegitation (High)      0.0
Vegitation (Low)       0.0
Temp                   0.0
Relative Humidity      0.0
PM10                   0.0
PM2.5                  0.0
NO2                    0.0
O3                     0.0
code                   0.0
id                     0.0
dtype: float64

In [35]:
df_athens['Wind_Speed'] = np.sqrt(df_athens['Wind-Speed (U)']**2 + df_athens['Wind-Speed (V)']**2)
df_athens

,Date,Latitude,Longitude,station_name,Wind-Speed (U),Wind-Speed (V),Dewpoint Temp,Soil Temp,Total Percipitation,Vegitation (High),Vegitation (Low),Temp,Relative Humidity,PM10,PM2.5,NO2,O3,code,id,Wind_Speed
0,2020-05-01 00:00:00,38.150000,23.550000,Athens CAMS station 0,1.713115,-0.588855,10.046454,17.083554,0.000035,1.699026,2.244626,12.948856,82.578812,8.101824,6.200135,3.479941,76.28401,ACAMS00,45,1.811495
1,2020-05-01 00:00:00,37.850000,23.750000,Athens CAMS station 9,1.960498,-0.937417,10.270286,17.909675,0.000037,1.743299,1.431182,14.011539,78.352731,10.520411,7.836725,17.563843,74.39110,ACAMS09,54,2.173086
2,2020-05-01 00:00:00,38.150000,23.650000,Athens CAMS station 1,1.640985,-0.556073,9.700422,16.976489,0.000040,1.642665,2.172998,12.550690,82.840317,8.587352,6.306404,2.892315,74.56569,ACAMS01,46,1.732642
3,2020-05-01 00:00:00,37.850000,23.850000,Athens CAMS station 10,2.003834,-0.971722,10.159251,17.993456,0.000036,1.753648,1.582832,14.261641,76.558915,10.917974,8.207660,17.196804,67.90412,ACAMS10,55,2.227015
4,2020-05-01 00:00:00,37.850000,23.950000,Athens CAMS station 11,1.954063,-0.912335,9.993532,17.957935,0.000036,1.706804,1.806660,14.179075,76.140202,11.353168,8.217451,15.817172,67.63471,ACAMS11,56,2.156552
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1726459,2023-05-29 23:00:00,37.932000,23.713000,SMYRNI,0.240230,-1.216293,13.464139,20.926649,0.000809,1.557783,1.392521,16.946201,79.994187,19.000000,20.736000,24.000000,62.00000,GR0031A,15,1.239790
1726460,2023-05-29 23:00:00,37.901000,23.879000,KOROPI,0.075186,-1.339309,13.110978,21.116500,0.000581,1.663799,2.290440,17.310772,76.371899,22.000000,12.737628,15.000000,58.00000,GR0120A,21,1.341418
1726461,2023-05-29 23:00:00,37.948063,23.728360,PANACEA_045,-0.012447,-4.024046,0.817448,16.663882,0.000117,1.462879,1.247304,17.860900,31.921052,20.490770,13.595480,9.606083,100.65001,PAN045,73,4.024065
1726462,2023-05-29 23:00:00,37.977210,23.783016,National Technical University of Athens,-0.491393,-3.956621,12.422827,20.905300,0.000786,1.469335,0.926387,22.035118,54.449878,14.873333,13.720000,5.000000,99.00000,NTUA01,101,3.987019
1726463,2023-05-29 23:00:00,37.978000,23.727000,ATHINAS,0.209901,-1.259627,13.790172,21.719023,0.000797,1.039985,1.013138,17.284556,79.951931,19.360000,18.053333,27.000000,9.00000,GR0027A,9,1.276996

In [36]:
df_athens['Point'] = df_athens.apply(lambda row: (row['Latitude'], row['Longitude']), axis=1)

df_athens = df_athens.drop(columns=['Latitude', 'Longitude'])

df_athens

,Date,station_name,Wind-Speed (U),Wind-Speed (V),Dewpoint Temp,Soil Temp,Total Percipitation,Vegitation (High),Vegitation (Low),Temp,Relative Humidity,PM10,PM2.5,NO2,O3,code,id,Wind_Speed,Point
0,2020-05-01 00:00:00,Athens CAMS station 0,1.713115,-0.588855,10.046454,17.083554,0.000035,1.699026,2.244626,12.948856,82.578812,8.101824,6.200135,3.479941,76.28401,ACAMS00,45,1.811495,"(38.15, 23.55)"
1,2020-05-01 00:00:00,Athens CAMS station 9,1.960498,-0.937417,10.270286,17.909675,0.000037,1.743299,1.431182,14.011539,78.352731,10.520411,7.836725,17.563843,74.39110,ACAMS09,54,2.173086,"(37.85, 23.75)"
2,2020-05-01 00:00:00,Athens CAMS station 1,1.640985,-0.556073,9.700422,16.976489,0.000040,1.642665,2.172998,12.550690,82.840317,8.587352,6.306404,2.892315,74.56569,ACAMS01,46,1.732642,"(38.15, 23.65)"
3,2020-05-01 00:00:00,Athens CAMS station 10,2.003834,-0.971722,10.159251,17.993456,0.000036,1.753648,1.582832,14.261641,76.558915,10.917974,8.207660,17.196804,67.90412,ACAMS10,55,2.227015,"(37.85, 23.85)"
4,2020-05-01 00:00:00,Athens CAMS station 11,1.954063,-0.912335,9.993532,17.957935,0.000036,1.706804,1.806660,14.179075,76.140202,11.353168,8.217451,15.817172,67.63471,ACAMS11,56,2.156552,"(37.85, 23.95)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1726459,2023-05-29 23:00:00,SMYRNI,0.240230,-1.216293,13.464139,20.926649,0.000809,1.557783,1.392521,16.946201,79.994187,19.000000,20.736000,24.000000,62.00000,GR0031A,15,1.239790,"(37.932, 23.713)"
1726460,2023-05-29 23:00:00,KOROPI,0.075186,-1.339309,13.110978,21.116500,0.000581,1.663799,2.290440,17.310772,76.371899,22.000000,12.737628,15.000000,58.00000,GR0120A,21,1.341418,"(37.901, 23.879)"
1726461,2023-05-29 23:00:00,PANACEA_045,-0.012447,-4.024046,0.817448,16.663882,0.000117,1.462879,1.247304,17.860900,31.921052,20.490770,13.595480,9.606083,100.65001,PAN045,73,4.024065,"(37.948063, 23.72836)"
1726462,2023-05-29 23:00:00,National Technical University of Athens,-0.491393,-3.956621,12.422827,20.905300,0.000786,1.469335,0.926387,22.035118,54.449878,14.873333,13.720000,5.000000,99.00000,NTUA01,101,3.987019,"(37.97721, 23.783016)"
1726463,2023-05-29 23:00:00,ATHINAS,0.209901,-1.259627,13.790172,21.719023,0.000797,1.039985,1.013138,17.284556,79.951931,19.360000,18.053333,27.000000,9.00000,GR0027A,9,1.276996,"(37.978, 23.727)"

In [37]:
pm25_edges = [0, 12.0, 35.4, 55.4, 150.4, 250.4, np.inf]
pm25_labels = ["Good", "Moderate", "Unhealthy for SG", "Unhealthy", "Very Unhealthy", "Hazardous"]

In [38]:
pm10_edges = [0, 54, 154, 254, 354, 424, np.inf]
pm10_labels = ["Good", "Moderate", "Unhealthy for SG", "Unhealthy", "Very Unhealthy", "Hazardous"]

In [39]:
def add_pm_bins(df, col, edges, labels, out_col):
    if col in df.columns:
        df[out_col] = pd.cut(df[col], bins=edges, labels=labels, include_lowest=True)
        print(f"Created {out_col} from {col}")
    else:
        print(f"Skipped: column '{col}' not found.")

In [40]:
add_pm_bins(df_athens, 'PM2.5', pm25_edges, pm25_labels, 'PM25_AQI_bin')
add_pm_bins(df_athens, 'PM10', pm10_edges, pm10_labels, 'PM10_AQI_bin')

Created PM25_AQI_bin from PM2.5
Created PM10_AQI_bin from PM10

In [41]:
df_athens

,Date,station_name,Wind-Speed (U),Wind-Speed (V),Dewpoint Temp,Soil Temp,Total Percipitation,Vegitation (High),Vegitation (Low),Temp,...,PM10,PM2.5,NO2,O3,code,id,Wind_Speed,Point,PM25_AQI_bin,PM10_AQI_bin
0,2020-05-01 00:00:00,Athens CAMS station 0,1.713115,-0.588855,10.046454,17.083554,0.000035,1.699026,2.244626,12.948856,...,8.101824,6.200135,3.479941,76.28401,ACAMS00,45,1.811495,"(38.15, 23.55)",Good,Good
1,2020-05-01 00:00:00,Athens CAMS station 9,1.960498,-0.937417,10.270286,17.909675,0.000037,1.743299,1.431182,14.011539,...,10.520411,7.836725,17.563843,74.39110,ACAMS09,54,2.173086,"(37.85, 23.75)",Good,Good
2,2020-05-01 00:00:00,Athens CAMS station 1,1.640985,-0.556073,9.700422,16.976489,0.000040,1.642665,2.172998,12.550690,...,8.587352,6.306404,2.892315,74.56569,ACAMS01,46,1.732642,"(38.15, 23.65)",Good,Good
3,2020-05-01 00:00:00,Athens CAMS station 10,2.003834,-0.971722,10.159251,17.993456,0.000036,1.753648,1.582832,14.261641,...,10.917974,8.207660,17.196804,67.90412,ACAMS10,55,2.227015,"(37.85, 23.85)",Good,Good
4,2020-05-01 00:00:00,Athens CAMS station 11,1.954063,-0.912335,9.993532,17.957935,0.000036,1.706804,1.806660,14.179075,...,11.353168,8.217451,15.817172,67.63471,ACAMS11,56,2.156552,"(37.85, 23.95)",Good,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1726459,2023-05-29 23:00:00,SMYRNI,0.240230,-1.216293,13.464139,20.926649,0.000809,1.557783,1.392521,16.946201,...,19.000000,20.736000,24.000000,62.00000,GR0031A,15,1.239790,"(37.932, 23.713)",Moderate,Good
1726460,2023-05-29 23:00:00,KOROPI,0.075186,-1.339309,13.110978,21.116500,0.000581,1.663799,2.290440,17.310772,...,22.000000,12.737628,15.000000,58.00000,GR0120A,21,1.341418,"(37.901, 23.879)",Moderate,Good
1726461,2023-05-29 23:00:00,PANACEA_045,-0.012447,-4.024046,0.817448,16.663882,0.000117,1.462879,1.247304,17.860900,...,20.490770,13.595480,9.606083,100.65001,PAN045,73,4.024065,"(37.948063, 23.72836)",Moderate,Good
1726462,2023-05-29 23:00:00,National Technical University of Athens,-0.491393,-3.956621,12.422827,20.905300,0.000786,1.469335,0.926387,22.035118,...,14.873333,13.720000,5.000000,99.00000,NTUA01,101,3.987019,"(37.97721, 23.783016)",Moderate,Good
1726463,2023-05-29 23:00:00,ATHINAS,0.209901,-1.259627,13.790172,21.719023,0.000797,1.039985,1.013138,17.284556,...,19.360000,18.053333,27.000000,9.00000,GR0027A,9,1.276996,"(37.978, 23.727)",Moderate,Good

In [42]:
df_athens["PM10_AQI_bin"].value_counts()

PM10_AQI_bin
Good                1639604
Moderate              83896
Unhealthy for SG       2614
Unhealthy               264
Very Unhealthy           56
Hazardous                30
Name: count, dtype: int64

In [43]:
df_athens["PM25_AQI_bin"].value_counts()

PM25_AQI_bin
Good                908327
Moderate            731471
Unhealthy for SG     63113
Unhealthy            21568
Very Unhealthy        1683
Hazardous              302
Name: count, dtype: int64

In [44]:
df_athens['Temperature_Binary'] = (df_athens['Temp'] > 15).astype(int)
df_athens

,Date,station_name,Wind-Speed (U),Wind-Speed (V),Dewpoint Temp,Soil Temp,Total Percipitation,Vegitation (High),Vegitation (Low),Temp,...,PM2.5,NO2,O3,code,id,Wind_Speed,Point,PM25_AQI_bin,PM10_AQI_bin,Temperature_Binary
0,2020-05-01 00:00:00,Athens CAMS station 0,1.713115,-0.588855,10.046454,17.083554,0.000035,1.699026,2.244626,12.948856,...,6.200135,3.479941,76.28401,ACAMS00,45,1.811495,"(38.15, 23.55)",Good,Good,0
1,2020-05-01 00:00:00,Athens CAMS station 9,1.960498,-0.937417,10.270286,17.909675,0.000037,1.743299,1.431182,14.011539,...,7.836725,17.563843,74.39110,ACAMS09,54,2.173086,"(37.85, 23.75)",Good,Good,0
2,2020-05-01 00:00:00,Athens CAMS station 1,1.640985,-0.556073,9.700422,16.976489,0.000040,1.642665,2.172998,12.550690,...,6.306404,2.892315,74.56569,ACAMS01,46,1.732642,"(38.15, 23.65)",Good,Good,0
3,2020-05-01 00:00:00,Athens CAMS station 10,2.003834,-0.971722,10.159251,17.993456,0.000036,1.753648,1.582832,14.261641,...,8.207660,17.196804,67.90412,ACAMS10,55,2.227015,"(37.85, 23.85)",Good,Good,0
4,2020-05-01 00:00:00,Athens CAMS station 11,1.954063,-0.912335,9.993532,17.957935,0.000036,1.706804,1.806660,14.179075,...,8.217451,15.817172,67.63471,ACAMS11,56,2.156552,"(37.85, 23.95)",Good,Good,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1726459,2023-05-29 23:00:00,SMYRNI,0.240230,-1.216293,13.464139,20.926649,0.000809,1.557783,1.392521,16.946201,...,20.736000,24.000000,62.00000,GR0031A,15,1.239790,"(37.932, 23.713)",Moderate,Good,1
1726460,2023-05-29 23:00:00,KOROPI,0.075186,-1.339309,13.110978,21.116500,0.000581,1.663799,2.290440,17.310772,...,12.737628,15.000000,58.00000,GR0120A,21,1.341418,"(37.901, 23.879)",Moderate,Good,1
1726461,2023-05-29 23:00:00,PANACEA_045,-0.012447,-4.024046,0.817448,16.663882,0.000117,1.462879,1.247304,17.860900,...,13.595480,9.606083,100.65001,PAN045,73,4.024065,"(37.948063, 23.72836)",Moderate,Good,1
1726462,2023-05-29 23:00:00,National Technical University of Athens,-0.491393,-3.956621,12.422827,20.905300,0.000786,1.469335,0.926387,22.035118,...,13.720000,5.000000,99.00000,NTUA01,101,3.987019,"(37.97721, 23.783016)",Moderate,Good,1
1726463,2023-05-29 23:00:00,ATHINAS,0.209901,-1.259627,13.790172,21.719023,0.000797,1.039985,1.013138,17.284556,...,18.053333,27.000000,9.00000,GR0027A,9,1.276996,"(37.978, 23.727)",Moderate,Good,1

In [45]:
df_athens["Temperature_Binary"].value_counts()

Temperature_Binary
1    981289
0    745175
Name: count, dtype: int64

In [46]:
df_athens.to_csv('athens_results.csv')

In [47]:
from statsmodels.tsa.seasonal import STL

def robust_zscore(x):
    x = np.asarray(x)
    med = np.median(x)
    mad = np.median(np.abs(x - med))
    if mad == 0:
        std = np.std(x)
        return (x - med) / std if std != 0 else np.zeros_like(x)
    return (x - med) / (1.4826 * mad)

ModuleNotFoundError: No module named 'statsmodels'

In [ ]:
def safe_name(colname):
    return str(colname).replace('.', '_').replace(' ', '_').replace('-', '_')

In [ ]:
def compute_zresids_stl(df,
                        dt_col='Date',
                        station_col='station_name',
                        vars_to_process=None,
                        period=24):

    if vars_to_process is None:
        vars_to_process = ['PM10', 'PM2.5', 'NO2', 'O3', 'Temp']

    df = df.copy()
    df[dt_col] = pd.to_datetime(df[dt_col])
    df = df.sort_values([station_col, dt_col])

    zframes = []

    for var in vars_to_process:
        if var not in df.columns:
            raise KeyError(f"Column '{var}' not found in dataframe")

        results = []
        for station, g in df.groupby(station_col, sort=False):
            s = g.set_index(dt_col)[var].astype(float)

            if len(s) < period * 2:
                # not enough data -> produce NaNs for zresid
                out = pd.DataFrame({'z_resid': [np.nan] * len(s)}, index=s.index)
            else:
                stl = STL(s, period=period, robust=True)
                res = stl.fit()
                resid = res.resid.values
                z = robust_zscore(resid)
                out = pd.DataFrame({'z_resid': z}, index=s.index)

            out = out.reset_index().rename(columns={dt_col: 'dt_index'})
            out[station_col] = station
            results.append(out)

        all_out = pd.concat(results, ignore_index=True).rename(columns={'dt_index': dt_col})
        colname = f"{safe_name(var)}_z_resid"
        all_out = all_out[[dt_col, station_col, 'z_resid']].rename(columns={'z_resid': colname})

        zframes.append(all_out)

    merged_z = None
    for zf in zframes:
        if merged_z is None:
            merged_z = zf
        else:
            merged_z = pd.merge(merged_z, zf, on=[dt_col, station_col], how='outer')

    df_out = pd.merge(df, merged_z, on=[dt_col, station_col], how='left')

    return df_out

In [ ]:
def apply_thresholds(df_with_z,
                     vars_to_process=None,
                     z_thresh=None,
                     dt_col='Date'):

    df = df_with_z.copy()
    if vars_to_process is None:
        zcols = [c for c in df.columns if c.endswith('_z_resid')]
        vars_to_process = [c[:-7].replace('_', '.') for c in zcols]

    if isinstance(z_thresh, dict):
        thresh_map = z_thresh
    else:
        thresh_map = {v: z_thresh for v in vars_to_process}

    for var in vars_to_process:
        suf = safe_name(var)
        zcol = f"{suf}_z_resid"
        if zcol not in df.columns:
            raise KeyError(f"Expected z-resid column '{zcol}' not found. Run compute_zresids_stl first.")

        t = thresh_map.get(var, thresh_map.get(suf, None))
        if t is None:
            raise ValueError(f"No threshold specified for variable '{var}' (provide z_thresh numeric or dict).")

        two_col = f"{suf}_outlier_two_sided"
        pos_col = f"{suf}_outlier_positive_spike"

        df[two_col] = df[zcol].abs() > t
        df[pos_col] = df[zcol] > t

        df[two_col] = df[two_col].fillna(False)
        df[pos_col] = df[pos_col].fillna(False)

    return df